### ISSUE TITLE
Any way to make this work with Gatsby Link?

### ISSUE THREAD

**Issue by daydream05** [freddydumont/gatsby-plugin-smoothscroll#3] opened 2020-03-03 17:53 UTC
Thanks for this plugin!

I'm trying to use this in comination with Gatsby Link but when I use `onClick={() => scrollTo(#slug)}` on Gatsby Link, it's not working. 

When I use a regular button, it works as intended but I want to utilize the Link component.

I think Link is overriding the behavior of smoothscroll.

**Comment by freddydumont** [comment] 2020-03-03 19:46
This plugin isn't made to work across routes, and [`Link` isn't made for in-route navigation](https://www.gatsbyjs.org/docs/gatsby-link/#recommendations-for-programmatic-in-app-navigation).

I'm not sure I understand your use case here. If it works as intended when using a regular button, why do you want to use `Link`?

**Comment by daydream05** [comment] 2020-03-05 00:32
Gotcha. I needed the [getProps](https://www.gatsbyjs.org/docs/gatsby-link/#use-getprops-for-advanced-link-styling) method from `Link` so I can style my table of contents when the url is on it. I saw the [gatsbyjs.org](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/docs-table-of-contents.jsl) using Link for in-route navigation so I just followed it.

I guess I need an alternative way of styling it.

**Comment by freddydumont** [comment] 2020-03-10 14:58
In any case I don't think this is within the scope of this package so I'm gonna close this issue. Feel free to submit a PR if you find a solution that suits your needs.

**Closed by freddydumont** 2020-03-10 14:58 UTC
